# Pulse meter configuration #

# Enable Home Assistant API
api:
  services:
    - service: reset_total_energy
      then:
        - button.press:
            id: button_reset_total_1
        - button.press:
            id: button_reset_total_2

number:
  # Set the pulse rate of the LED on your meter
  - platform: template
    id: select_pulse_rate
    name: 'Puls rate - imp/kWh'
    optimistic: true
    mode: box
    min_value: 100
    max_value: 10000
    step: 100
    restore_value: yes
    initial_value: 1000

  # Reset total energy to given value
  - platform: template
    id: select_reset_total_1
    name: 'Reset Value 1 - Total Energy kWh'
    entity_category: config
    optimistic: true
    mode: box
    min_value: 0
    max_value: 1000000
    step: 1
    initial_value: 0
  - platform: template
    id: select_reset_total_2
    name: 'Reset Value 2 - Total Energy kWh'
    entity_category: config
    optimistic: true
    mode: box
    min_value: 0
    max_value: 1000000
    step: 1
    initial_value: 0

button:
  # Reset the total energy entity
  - platform: template
    id: button_reset_total_1
    name: "Reset 1 - Total Energy"
    on_press:
      - pulse_meter.set_total_pulses:
          id: sensor_energy_pulse_meter_1
          value: !lambda "return id(select_reset_total_1).state * id(select_pulse_rate).state;"
  - platform: template
    id: button_reset_total_2
    name: "Reset 2 - Total Energy"
    on_press:
      - pulse_meter.set_total_pulses:
          id: sensor_energy_pulse_meter_2
          value: !lambda "return id(select_reset_total_2).state * id(select_pulse_rate).state;"
          
sensor:
  # Pulse meter
  - platform: pulse_meter
    id: sensor_energy_pulse_meter_1
    name: '${friendly_name} - Power Consumption 1'
    unit_of_measurement: W
    state_class: measurement
    device_class: power
    icon: mdi:flash-outline
    accuracy_decimals: 0
    pin: ${pulse_pin_1}
    on_raw_value:
      then:
        - light.turn_on:
            id: led_red
        - delay: 0.2s
        - light.turn_off:
            id: led_red
    filters:
      # multiply value = (60 / imp value) * 1000
      # - multiply: 60
      - lambda: return x * ((60.0 / id(select_pulse_rate).state) * 1000.0);
    total:
      id: sensor_total_energy_1
      name: '${friendly_name} - Total Energy 1'
      unit_of_measurement: kWh
      icon: mdi:circle-slice-3
      state_class: total_increasing
      device_class: energy
      accuracy_decimals: 3
      filters:
        # multiply value = 1 / imp value
        # - multiply: 0.001
        - lambda: return x * (1.0 / id(select_pulse_rate).state);
  
  - platform: pulse_meter
    id: sensor_energy_pulse_meter_2
    name: '${friendly_name} - Power Consumption 2'
    unit_of_measurement: W
    state_class: measurement
    device_class: power
    icon: mdi:flash-outline
    accuracy_decimals: 0
    pin: ${pulse_pin_2}
    on_raw_value:
      then:
        - light.turn_on:
            id: led_green
        - delay: 0.2s
        - light.turn_off:
            id: led_green
    filters:
      # multiply value = (60 / imp value) * 1000
      # - multiply: 60
      - lambda: return x * ((60.0 / id(select_pulse_rate).state) * 1000.0);

    total:
      id: sensor_total_energy_2
      name: '${friendly_name} - Total Energy 2'
      unit_of_measurement: kWh
      icon: mdi:circle-slice-3
      state_class: total_increasing
      device_class: energy
      accuracy_decimals: 3
      filters:
        # multiply value = 1 / imp value
        # - multiply: 0.001
        - lambda: return x * (1.0 / id(select_pulse_rate).state);

  # Total day usage
  - platform: total_daily_energy
    id: sensor_total_daily_energy_1
    name: '${friendly_name} - Daily Energy 1'
    power_id: sensor_energy_pulse_meter_1
    unit_of_measurement: kWh
    icon: mdi:circle-slice-3
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
  - platform: total_daily_energy
    id: sensor_total_daily_energy_2
    name: '${friendly_name} - Daily Energy 2'
    power_id: sensor_energy_pulse_meter_2
    unit_of_measurement: kWh
    icon: mdi:circle-slice-3
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
